name: Deploy Next.js App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files via SSH
        run: |
          ssh -o StrictHostKeyChecking=no root@147.182.188.127 'rm -rf /var/www/seatlynx/*'
          scp -o StrictHostKeyChecking=no -r * root@147.182.188.127:/var/www/seatlynx

      - name: Install dependencies and restart server
        run: |
          ssh -o StrictHostKeyChecking=no root@147.182.188.127 << 'EOF'
          cd /var/www/seatlynx
          yarn install
          pm2 restart server
          EOF
